#!/bin/sh

# run certbot (checks for existing cert and renews if needed)
certbot certonly --dns-cloudflare --dns-cloudflare-credentials ~/.secrets/cloudflare.ini -d <DOMAIN> --preferred-challenges dns-01 --non-interactive

# copy in new cert
rsync -L -avz -e 'ssh -i /home/packetfence/.ssh/id_rsa' /etc/letsencrypt/live/freepbx.armchairsavages.net/cert.pem          root@freepbx.armchairsavages.net:/etc/httpd/pki/webserver.crt
rsync -L -avz -e 'ssh -i /home/packetfence/.ssh/id_rsa' /etc/letsencrypt/live/freepbx.armchairsavages.net/fullchain.pem     root@freepbx.armchairsavages.net:/etc/httpd/pki/webserver.pem
rsync -L -avz -e 'ssh -i /home/packetfence/.ssh/id_rsa' /etc/letsencrypt/live/freepbx.armchairsavages.net/privkey.pem       root@freepbx.armchairsavages.net:/etc/httpd/pki/webserver.key

# set permissions on new cert files
ssh -i /home/packetfence/.ssh/id_rsa root@freepbx.armchairsavages.net 'chown asterisk:asterisk /etc/httpd/pki/webserver.crt'
ssh -i /home/packetfence/.ssh/id_rsa root@freepbx.armchairsavages.net 'chown asterisk:asterisk /etc/httpd/pki/webserver.pem'
ssh -i /home/packetfence/.ssh/id_rsa root@freepbx.armchairsavages.net 'chown asterisk:asterisk /etc/httpd/pki/webserver.key'

# import cert and set as default
ssh -i ~/.ssh/id_rsa <USER>@<HOST> 'fwconsole certificates --import'
ssh -i ~/.ssh/id_rsa <USER>@<HOST> 'fwconsole certificates --default=freepbx'

# reload asterisks
ssh -i ~/.ssh/id_rsa <USER>@<HOST> 'fwconsole reload'

# restart apache
ssh -i ~/.ssh/id_rsa <USER>@<HOST> 'systemctl reload httpd'
